source 'https://rubygems.org'

gem 'activesupport'
gem 'curses'
gem 'jason-math', git: 'https://github.com/jasoncolburne/jason-math', branch: 'main'
gem 'rest-client'
gem 'rubocop'
gem 'pry'
gem 'sinatra'
gem 'thin'
